M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Do 10 Aug 2023 10:53:23 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-10T10:53:23+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X156.285Y-64.125
X167.715Y-64.125
T2
X116.751Y-93.504
X116.751Y-131.504
X180.251Y-131.504
T0
M30
